Ercess/urls.py
from django.contrib import admin
from django.conf.urls import  url
from Ercesscorp import  views
from django.urls import  path ,re_path ,include
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from Ercesscorp.apiviews import *
from dashboard import url_shortner

# app_name = 'Ercess'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin-site/',include('admin_panel.urls')),

    url(r'^$', views.home , name='home'),
    url(r'^accounts/login/$',views.loginview ,name='login'),
    url(r'^live/dashboard/', include('dashboard.urls')),
   # url(r'^live/dashboard/organizer_dashboard',views.manageevents),
    url(r'^home/$', views.home, name='home'),
    url(r'^live/$',views.home , name='home'),
    url(r'^live/verify_email/(?P<slug>[\w-]+)/$', views.verify_mail),
#    url(r'^live/verify_email/$', views.verify_mail, name='verify-email'),
    url(r'^live/forgot_password/$', views.forgotPassword, name='forgot-password'),
    url(r'^live/reset_password/(?P<slug>[\w-]+)/$', views.resetPassword),
    url(r'^live/set_new_password/$', views.setNewPassword),
#    url(r'^live/reset_password/$', views.resetPassword,name='reset-password'),
    url(r'^live/login/$', views.loginview, name='login'),
    url(r'^live/logout/$', views.logoutview, name='logout'),
    url(r'^live/signup/$', views.registration,name='signup'),
    url(r'^live/multichannel/$',views.multichannelpromotion,name='multichannel-promotion'),
    url(r'^live/sell-event-stalls/$',views.sellstallspaces, name='sell-event-stalls'),
    url(r'^live/paid-advertisement/$', views.advertisement,name='advertisement'),
    url(r'^live/how-it-works/$',views.howitworks, name='how-it-works'),
    url(r'^live/about/$',views.aboutus,name='about-us'),
    url(r'^live/contact/$',views.contactus,name='contact-us'),
    url(r'^live/blogs/$', views.blog, name='blog'),
    url(r'^live/blog-post/(?P<pk>[0-9]+)$', views.blogpost,name='blog-post'),
    url(r'^live/careers/$', views.career, name='careers'),
    url(r'^live/pricing/$', views.pricing, name='pricing'),
    url(r'^live/partners/$', views.partners, name='partners'),
    url(r'^live/privacy-policy/$', views.privacypolicy , name='privacy-policy'),
    url(r'^live/api/blogs/$' , BlogDetails.as_view(),name='blog-details'),
    url(r'^live/api/blogs/(?P<pk>[0-9]+)$', BlogSpecific.as_view(),name='blogspecific'),
    url(r'^live/api/users/$', Reg.as_view(),name='reg'),
    url(r'^live/api/login/$', LoginView.as_view(),'loginview'),
    url(r'^live/case-studies/$',views.case_studies, name='case-studies'),
    url(r'^live/cashback-info/(?P<slug>[\w-]+)$', views.provideCashbackDetails),
    url(r'^short-url/(?P<slug>[\w-]+)$', url_shortner.expand_url),

]

if settings.DEBUG:
    
    import debug_toolbar
    
    urlpatterns = [
      url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path, include
from django.conf.urls import  url
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.views.generic import TemplateView

from Ercesscorp.third_party_security import smartlogin
from Ercesscorp import views
from Ercesscorp.views import edit_event,step_three,edit_event_two,edit_event_four,edit_event_five,edit_action_four,edit_action_four,edit_action_five,new_ticket
from dashboard.api.views import StallCreateAPIView, FacilitiesAPIView, StallUploadAPIView, StallUpdateAPIView, \
    EventSuccessView
from dashboard.views import getHow, change_password # , third_step#,photo_list ,fourth_step
from .api.views import ( ArticlesCreateAPIView, CategoryCreateAPIView,
                        TopicsListAPIView, DescriptionCreateAPIView,
                        ThirdStepTemp, QuestionCreateAPIView,
                        CreateTicketsView, BankDetailsView, EditBankDetailsView)

from .views import  EditDetailView


app_name = 'dashboard'

urlpatterns = [
    url(r'^$', getHow, name='how'),
    path('create-stall-step1/<int:event_id>/', FacilitiesAPIView.as_view(), name='facilities'),
    path('create-stall-step2/<int:event_id>/', StallUploadAPIView.as_view(), name='stall_upload'),
    path('create-stalls/<int:event_id>/', StallCreateAPIView.as_view(), name='create_stall'),
    path('update-stalls/<int:event_id>/', StallUpdateAPIView.as_view(), name='stall_update'),

    path('add-event', ArticlesCreateAPIView.as_view(), name="step_one"),
    path('add-event-types/<str:md5>/<int:event_id>', CategoryCreateAPIView.as_view(), name="step_two"),
    path('add-event-images/<str:md5>/<int:event_id>', views.step_three, name="step_three"),
    # path('add-event-images-action/<str:md5>/<int:event_id>', views.step_three_action, name="step_three_action"),
    path('ajax/topics', TopicsListAPIView.as_view()),
    path('add-event-description/<str:md5>/<int:event_id>', DescriptionCreateAPIView.as_view(), name="step_four"),
    path('add-event-tickets/<str:md5>/<int:event_id>', CreateTicketsView.as_view(), name="step_five"),
    path('add-event-question/<str:md5>/<int:event_id>', QuestionCreateAPIView.as_view(), name="step_six"),
    path('stall_added/', TemplateView.as_view(template_name='stall/stall_success.html'), name='stall_added'),
    path('event_added/<int:event_id>/', EventSuccessView.as_view(), name='event_added'),
    path('RSVP',views.RSVP,name='leads'),
    path('updateContact/',views.updateMobileNo, name="updateContact"),
    path('rsvp/<int:event_id>',views.rsvp_event,name='rsvp-event'),
    path('organizer_dashboard',views.manageevents, name='organizer-dashboard'),
    path('event-details/<int:event_id>',views.event_details, name='event-details'),
    path('sales', views.getSales, name='sales'),
    path('sales_details/<int:event_id>/',views.getSalesDetails, name ='sale_details'),
    path('inquiries', views.getInquiries, name='inquiries'),
    path('help',views.getHelp,name='help'),
    path('profile',views.profile,name='profile'),
    path('settings', change_password,name='settings'),
    path('legal',views.legal,name='legal'),
    path('organizer-agreement',views.organizer_agreement,name='organizer-agreement'),
    path('bank-details',BankDetailsView.as_view(), name="bank_details"),
    # path('create-stalls',views.create_stall, name="create_stall"),
    path('edit-event/<int:event_id>', EditDetailView.as_view(), name="detail"),
    path('boost-event/<int:event_id>', views.boost, name="boost-event"),
    path('edit-event/basic/<int:event_id>',views.edit_event, name='edit-event'),
    path('edit-event-two/<int:event_id>',views.edit_event_two, name='edit-event-two'),
    # path('edit-event-three/<int:event_id>',views.edit_event_three, name='edit-event-three'),
    path('edit-event-four/<int:event_id>',views.edit_event_four, name='edit-event-four'),
    path('edit-event-five/<int:event_id>/<int:ticket_id>',views.edit_event_five, name='edit-event-five'),
    path('edit_event_ticket/<event_id>',views.edit_event_ticket, name='edit-event-ticket'),
    path('new_ticket/<int:event_id>',views.new_ticket, name='new-ticket'),
    path('edit_action_two/<event_id>',views.edit_action_two, name='edit-action-two'),
    path('edit_action_five/<event_id>/<int:ticket_id>',views.edit_action_five, name='edit-action-five'),
    path('edit_action_four/<event_id>',views.edit_action_four, name='edit-action-four'),
    path('delete_ticket/<str:md5>/<int:event_id>/<int:ticket_id>/<int:return_page>',views.delete_ticket, name='delete-ticket'),
    path('update_event_tickets/<str:md5>/<int:event_id>/<int:ticket_id>',views.update_event_tickets, name='update-event-tickets'),
    path('edit_event_three/<int:event_id>',views.edit_event_three, name='edit-event-three'),
    path('edit-bank-details',EditBankDetailsView.as_view(), name="edit_bank_details"),
    # path('unlock-rsvp/<int:event_id>/<int:table_id_par>',views.unlock_rsvp,name='unlock-rsvp'),
    # path('subscribe-premium-package/<int:event_id>/<int:table_id_par>/<charges_id_par>',views.subscribe_premium_package,name='subscribe-premium-package'),
    # path('payment-success-rsvp',views.payment_success_rsvp,name='payment-success-rsvp'),
    # path('payment-fail-rsvp',views.payment_fail_rsvp,name='payment-fail-rsvp'),
    
    # urls for duplicate events
    path('duplicate-event-basics/<int:event_id>', views.duplicate_event_basics,name='duplicate-event-basics'),
    path('duplicate-event-two/<int:old_event_id>/<int:new_event_id>', views.duplicate_event_two,name='duplicate-event-two'),
    path('duplicate-event-three/<int:old_event_id>/<int:new_event_id>', views.duplicate_event_three,name='duplicate-event-three'),
    path('duplicate-event-four/<int:old_event_id>/<int:new_event_id>', views.duplicate_event_four,name='duplicate-event-four'),
    path('duplicate-event-five/<int:old_event_id>/<int:new_event_id>/<int:ticket_id>', views.duplicate_event_five,name='duplicate-event-five'),
    path('duplicate-event-tickets/<int:old_event_id>/<int:new_event_id>', views.duplicate_event_tickets,name='duplicate-event-tickets'),
    path('save-duplicate-event-five', views.save_duplicate_event_five,name='save-duplicate-event-five'),
    path('duplicate-new-ticket/<int:old_event_id>/<int:new_event_id>', views.duplicate_new_ticket,name='duplicate-new-ticket'),
    path('duplicate-event-six/<int:old_event_id>/<int:new_event_id>', views.duplicate_event_six,name='duplicate-event-six'),
    # ends here ~ urls for duplicate events

    path('check-event-already-created', views.check_event_already_created,name='check-event-already-created'),
    path('check-event-already-created-edit', views.check_event_already_created_edit,name='check-event-already-created-edit'),
    path('update-ann-access-table', views.updateAnnAccessTable,name='update-ann-access-table'),
    path('show-rsvp-premium-packages/<int:event_id>/<str:service_type>/<str:purpose_of_payment>',views.show_rsvp_premium_packages,name='show-rsvp-premium-packages'),
    
    # urls for payment package
    #IMPORTANT NOTE (For PAYUMONEY PAYMENT GATEWAY): All parameter name which start wifh udf's, that is temporary because we don't know about next values.. must need to change in future if include more values (e.g, now, udf2=event_id and udf3=charges_id) & MAX 10 UDF is allowed by PayUMoney
    path('buy-premium-package/<int:event_id>/<int:charges_id>/<int:udf4>/<int:udf5>/<str:purpose_of_payment>',views.buy_premium_package,name='buy-premium-package'),
    path('package-payment-success',views.package_payment_success,name='package-payment-success'),
    path('package-payment-fail',views.package_payment_fail,name='package-payment-fail'),
    # ends here ~ urls for payment package

    # sms marketing urls
    path('sms-marketing-initial-details/<int:event_id>',views.sms_marketing_initial_details,name='sms-marketing-initial-details'),
    path('sms-marketing-advance-details/<int:event_id>/<int:template_id>',views.sms_marketing_advance_details,name='sms-marketing-advance-details'),
    path('sms-marketing-schedule',views.sms_marketing_schedule,name='sms-marketing-schedule'),
    # ends here ~ sms marketing urls

    # email marketing urls
    path('select-email-marketing-template/<int:event_id>',views.select_email_marketing_template,name='select-email-marketing-template'),
    path('email-marketing-initial-details/<int:event_id>/<str:template_name>',views.email_marketing_initial_details,name='email-marketing-initial-details'),
    path('email-marketing-advance-details/<int:event_id>/<int:campaign_template_id>',views.email_marketing_advance_details,name='email-marketing-advance-details'),
    path('email-marketing-schedule',views.email_marketing_schedule,name='email-marketing-schedule'),
    # ends here ~ email marketing urls





    # path('buy-premium-package/<int:event_id>/<charges_id_par>',views.buy_premium_package,name='buy-premium-package'),
    # path('package-payment-success',views.package_payment_success,name='package-payment-success'),
    # path('package-payment-fail',views.package_payment_fail,name='package-payment-fail'),
    # path('buy-premium-package/<int:event_id>',views.buy_package_manage_events_dashboard,name='buy-package-manage-events-dashboard'),

    # path('edit-event-five/<int:event_id>/<int:ticket_id>/<str:md5>/<int:return_page>',views.edit_event_five, name='edit-event-five'),
    
    # path('delete_ticket/<int:event_id>/<int:ticket_id>',views.delete_ticket, name='delete-ticket'),



    #path('legal',views.legal,name='legal'),
    #url(r'create-event/step-three/(?P<eventid>[0-9]+)$',login_required(third_step),name='third-step'),
    #url(r'test$',photo_list),
    #url(r'create-event/step-four/$',login_required(fourth_step),name='fourth-step')
    # url(r'^home',home,name='home'),

templates/dashboard/create-event/step_1/address2.html
<div class="row">
    <div class="col-md-6 col-lg-6 col-sm-6 col-xs-12">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="input-group mb-3">
                        <input name="address_line2" id="route" type="text" class="form-control neighborhood sublocality_level_1  administrative_area_level_4 administrative_area_level_2" placeholder="Address Line 2*" readonly>
                        <div class="input-error alert alert-danger"></div>
                    </div>
                </div>
            </div>
        </div>

templates/dashboard/create-event/step_1/country.html
<div class="row">
    <div class="col-md-6 col-lg-6 col-sm-6 col-xs-6">
        <div class="form-group">
            <div class="input-group mb-3">
                <input name="country" id="country" type="text" class="form-control country" placeholder="Country*" readonly>
                <div class="input-error alert alert-danger"></div>
            </div>
        </div>
    </div>

templates/dashboard/create-event/step_1/enddate.html
<div class="row">
	<div class="col-md-6">
        <div class="form-group">
        	<div class="input-group mb-3">
            <input name="edate" class="form-control" id="enddatepicker" type="text" placeholder="End Date*">
            <div class="input-error alert alert-danger"></div>
            </div>
        </div>
    </div>

templates/dashboard/create-event/step_1/etime.html
<div class="col-md-6">
    <div class="form-group">
        <div class="input-group mb-3">
            <input name="end_time" id="timepicker1" class="input-small form-control" placeholder="End Time*" type="text">
        	<div class="input-error alert alert-danger"></div>
        </div>
    </div>
</div>
</div>



<script>
$('#timepicker').datetimepicker({
format: 'LT',
stepping : 5 });
$('#timepicker1').datetimepicker({
format: 'LT',
stepping : 5 });
$("#enddatepicker").keydown(function(e){
    e.preventDefault();
});
$("#datepicker").keydown(function(e){
    e.preventDefault();
});
$("#timepicker").keydown(function(e){
    e.preventDefault();
});
$("#timepicker1").keydown(function(e){
    e.preventDefault();
});



$('#datepicker').on('change', function() {
    function convertInputtoDate(){
    var input = document.getElementById("datepicker").value;
    var date = input.split('/');
    var selectdate = new Date(date[2]+"-"+ date[1]+"-"+ date[0]);

    return selectdate;
}
var today = convertInputtoDate();
var tomorrow = new Date(convertInputtoDate());
tomorrow.setDate(today.getDate());
$('#enddatepicker').datepicker('setStartDate', tomorrow);
});

</script>

templates/dashboard/create-event/step_1/eventname.html
<div class="row">
	<div class="col-md-6">
		<div class="form-group">
			<div class="input-group mb-3">
				{% if event_name %}
				<input name="event_name" type="text" class="form-control" value="{{event_name}}" >
				<div class="input-error alert alert-danger"></div>
				{% else %}
				<input name="event_name" type="text" class="form-control" placeholder="Event Name*{{event_name}}">
				<div class="input-error alert alert-danger"></div>
				{% endif %}
			</div>
		</div>
	</div>

templates/dashboard/create-event/step_1/latitude.html
 <input name="latitude" id="" type="hidden" class="form-control" >

templates/dashboard/create-event/step_1/longitude.html
 <input name="longitude" id="" type="hidden" class="form-control" >

templates/dashboard/create-event/step_1/place_id.html
<input name="place_id" id="" type="hidden" class="form-control" >

templates/dashboard/create-event/step_1/startdate.html
<div class="row">
	<div class="col-md-6">
		<div class="form-group">
        	<div class="input-group mb-3">
            	<input name="sdate" type="text" class="form-control" id="datepicker" placeholder="Start Date*">
				<div class="input-error alert alert-danger"></div>
			</div>
		</div>
	</div>

templates/dashboard/create-event/step_1/step_one.html
{% extends "dashboard/create_event.html" %}
{% load rest_framework %}

{% block title %}Create your event - Ercess Live{% endblock title %}
{% block step_one %}

  <div id="showDuplicateError"></div>
  

<section class="content">
    <div class="container arrow-steps clearfix">
        <div class="row heading">
            <div class="col-md-12 border-bottom-heading">
                <h1 class="text-dark pb-20 pt-20">Create Facilities</h1>
                <!-- <div class="md-stepper-horizontal red">
                    <div class="md-step active">
                      <div class="md-step-circle"><span>1</span></div>
                      <div class="md-step-title">Basic details</div>
                      <div class="md-step-bar-left"></div>
                      <div class="md-step-bar-right"></div>
                    </div>
                    <div class="md-step">
                      <div class="md-step-circle"><span>2</span></div>
                      <div class="md-step-title">Set targets</div>
                      <div class="md-step-bar-left"></div>
                      <div class="md-step-bar-right"></div>
                    </div>
                    <div class="md-step">
                      <div class="md-step-circle"><span>3</span></div>
                      <div class="md-step-title">Upload images</div>
                      <div class="md-step-bar-left"></div>
                      <div class="md-step-bar-right"></div>
                    </div>
                    <div class="md-step">
                      <div class="md-step-circle"><span>4</span></div>
                      <div class="md-step-title">Description</div>
                      <div class="md-step-bar-left"></div>
                      <div class="md-step-bar-right"></div>
                    </div>
                    <div class="md-step">
                      <div class="md-step-circle"><span>5</span></div>
                      <div class="md-step-title">Add tickets</div>
                      <div class="md-step-bar-left"></div>
                      <div class="md-step-bar-right"></div>
                    </div>
                    <div class="md-step">
                      <div class="md-step-circle"><span>6</span></div>
                      <div class="md-step-title">Custom questions</div>
                      <div class="md-step-bar-left"></div>
                      <div class="md-step-bar-right"></div>
                    </div>
                </div> -->
            </div>
        </div>
        <div class="row">
            {% if flag %}
              {% if serializer.errors %}
                {% for key,value in serializer.errors.items %}
                  <div class="alert alert-danger">
                     <strong style="color: white">{{ key|title }} : {{ value.0 }}</strong>
                  </div>
                {% endfor %}
              {% endif %}
            {% endif %}

            <form action="{% url 'dashboard:step_one' %}" method="POST" id="msform123" class="col-md-12 mt-20 pb-50" autocomplete="off">    {% csrf_token %}
                <fieldset>
                    {% render_form serializer template_pack='rest_framework/vertical' %}

                    <p>By clicking this button, you agree to our <a href="{% url 'dashboard:organizer-agreement' %}" target="_blank">legal business agreement</a>.</p>
                    <div class="text-center">
                        <a id="btn123" class="btn btn-danger mt-40">Create Event</a>
                        <!-- <button type="submit" id="btn123" class="btn btn-danger mt-40">Create Event</button> -->
                    </div>

                </fieldset>
            </form>
        </div>
    </div>

</section>
<script>


   // $('#id_venue_not_decided').change(function () {
   //    let venueVal = $('#id_venue_not_decided').val()
   //
   //    if(venueVal == 'false' || venueVal == false) {
   //      venueVal = true
   //    } else {
   //      venueVal = false
   //    }
   //
   //    $('#id_venue_not_decided').val(venueVal)
   // });
   //
   // custom required validation
   $.validator.addMethod("customRequired", function(elementVal, element) {
      let venueVal = false
      if(venueVal == 'false' || venueVal == false) {
        if(elementVal.trim() == '') {
          return false
        } else {
          return true
        }
      } else {
        return true
      }
    }, "This field is required");
   // ends here ~ custom required validation

    function convertInputtoDate(){
      var input = document.getElementById("datepicker").value;
      var date = input.split('/');
      var selectdate = new Date(date[2]+"-"+ date[1]+"-"+ date[0]);

      return selectdate;
    }

    // function for tomorrow date
     function tomorrow() {
       let today = new Date();
       let tomorrow = new Date();
       tomorrow.setDate(today.getDate() + 1);
       return tomorrow
    }
    // ends here ~ function for tomorrow date

    // function for get next day date
    function nextDayDate() {
       let today = convertInputtoDate();
       let tomorrow = new Date(convertInputtoDate());
       tomorrow.setDate(today.getDate() + 1);
       return tomorrow
    }
    // ends here ~ function for get next day date

     //startdate
     $('#datepicker').datepicker({
        format: 'dd/mm/yyyy',
        startDate: tomorrow()
    })

    $('#enddatepicker').datepicker({
    //  weekStart: 1,
         format: 'dd/mm/yyyy',
          startDate: tomorrow()
    })

//starttime
$('#timepicker').datetimepicker({
format: 'LT',

})

//endtime
$('#timepicker1').datetimepicker({
format: 'LT'

})

//custom-method-to compare start and end date
$.validator.addMethod("enddate", function(enddatevalue, element) {
var startdatevalue = $('#datepicker').val();
    var arrsdate = startdatevalue.split('/');
    var arredate = enddatevalue.split('/');
return new Date(arrsdate[2], arrsdate[1], arrsdate[0]) <= new Date(arredate[2],arredate[1],arredate[0]);
}, "End date can not be less than Start Date.");

//custom-method-to compare start and end time for same day event
$.validator.addMethod("endtime", function(endtimevalue, element) {
var startdatevalue = $('#datepicker').val();
var enddatevalue = $('#enddatepicker').val();

if(startdatevalue == enddatevalue){
    var temp = '01/01/1990'
    var starttimevalue = $('#timepicker').val();
    var st = new Date(temp + " " +starttimevalue).getTime();
    var et = new Date(temp + " " +endtimevalue).getTime();
    return et > st;
} else{
  return true;
}

}, "End Time can not be less than Start Time for same day event.");

$.validator.addMethod("web", function(webvalue, element) {
if(webvalue.length > 8){
    return true;
}
else{
    return false;
}

}, "Website link should start with https://");

function checkEventDuplicate() {
    let formObject = {}
    $("#msform123").serializeArray().map(function(x){formObject[x.name] = x.value;})
    let ajaxData = formObject
    // console.log(ajaxData)
    $.ajax({
        type: 'POST',
        url: "/live/dashboard/check-event-already-created",
        data: {'completeData':JSON.stringify(ajaxData)},
        dataType: "json",
        success: function(resp){
          let response = resp;
          if(response.responseType == 'success') {
              if(response.messageType == 'success') {
                $("#msform123").submit();
              } else if(response.messageType == 'error') {
                  $('#showDuplicateError').html(`<div class="alert alert-danger"><strong style="color: white"> ${response.message}</strong></div>`);
                  $('#showDuplicateError').show();
                  setTimeout(function() {
                      $("#showDuplicateError").hide('blind', {}, 500)
                  }, 10000);
              }
          }
      }
    });

}

$("#btn123").click(function ()
{

  form = $("#msform123");

  form.validate(
  {

    // errorElement: 'div',
    // errorClass: 'input-error alert alert-danger has_error',

    rules:
    {
      event_name:
      {
        required: true,
        minlength: 5,
        maxlength: 200,
        evtNameSpclValid: true,
        eventNameValidation: true,
        eventNameContValidation: true
      },
      website:
      {
        // web:true,
        required: true,
        url: true,
        maxlength: 500
      },
      sdate:
      {
        required: true,
      },
      edate:
      {
        required: true,
        enddate: true,
      },
      start_time:
      {
        required: true,
      },
      end_time:
      {
        required: true,
        endtime: true,
      },
      address_line1:
      {
        customRequired: true,
      },
      city:
      {
        customRequired: true,
      },
      state:
      {
        customRequired: true,
      },
      country:
      {
        customRequired: true,
      },
      pincode:
      {
        customRequired: true,
      },
    },
    highlight: function (element)
    {
      // add a class "has_error" to the element
      $(element).next('div').addClass('has_error');
    },
    unhighlight: function (element)
    {
      // remove the class "has_error" from the element
      $(element).next('div').removeClass('has_error');
    },
    messages:
    {
      event_name:
      {
        required: "Please enter name of your event",
        minlength: "Event name should have at least 5 characters"
      },
      website:
      {
        required: "Please enter website link",
      },
      sdate:
      {
        required: "Please select the Start Date of event",
      },
      edate:
      {
        required: "Please select the End Date of event",
        enddate: "End Date cannot be less than Start Date"
      },
      start_time:
      {
        required: "Please select the Start Time of event",
      },
      end_time:
      {
        required: "Please select the End Time of event",
        endtime: "End Time can not be less than Start Time for same day event"
      },
      address_line1:
      {
        required: "Please enter proper address of the event",
      }


    },
    success: function (error, element)
    {
      error.remove();
      $(element).next('div').removeClass('has_error');
      $(element).next('div').hide();
    },
    errorPlacement: function (error, element)
    {

      error.appendTo(element.next('div'));
      element.next('div').show();


    }

  });

  if(form.valid()) {
    checkEventDuplicate()
  }

});

//   $("#msform123").on('submit', function(e) {
//     $("#msform123").validate();
//     var isvalid = $("#msform123").valid();
//     if (isvalid) {
//         e.preventDefault();
//         alert(isvalid);
//     }
// });


// event name validation
$.validator.addMethod("eventNameValidation", function(eventNameVal, element) {
    return /^([a-zA-Z0-9]+\s)*[a-zA-Z0-9]+$/.test(eventNameVal)
}, "Remove unwanted blank spaces from the event name");
// ends here ~ event name validation

// event name sepcial character validation
$.validator.addMethod("evtNameSpclValid", function(eventNameVal, element) {
    if(/([!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?])/.test(eventNameVal)) {
      return false;
    } else {
      return true;
    }
}, "Special characters are not allowed in Event Name");
// ends here ~ event name sepcial character validation

// check contact details content
 var re_email = /(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))/;

var re_phn = /[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}/im;

var re_url = /((https?|ftp|smtp):\/\/)?(www.)?[a-z0-9]+(\.[a-z]{2,}){1,3}(#?\/?[a-zA-Z0-9#]+)*\/?(\?[a-zA-Z0-9-_]+=[a-zA-Z0-9-%]+&?)?/;

// contact details validation
$.validator.addMethod("eventNameContValidation", function(eventNameVal, element) {
    console.log(re_email.test(eventNameVal)|| re_phn.test(eventNameVal))
    let modifiedEventName = eventNameVal.trim().replace(/[^A-Z0-9,]/ig, "")
    if (re_email.test(eventNameVal)|| re_phn.test(modifiedEventName)|| re_url.test(eventNameVal)) {
      return false;
    } else {
      return true
    }
}, "Event Name should not contain any contact details");
// ends here ~ contact details validation

// ends here ~ check contact details content

</script>


{% endblock step_one %}