Ercess/urls.py
from django.contrib import admin
from django.conf.urls import  url
from Ercesscorp import  views
from django.urls import  path ,re_path ,include
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from Ercesscorp.apiviews import *
from dashboard import url_shortner

# app_name = 'Ercess'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin-site/',include('admin_panel.urls')),

    url(r'^$', views.home , name='home'),
    url(r'^accounts/login/$',views.loginview ,name='login'),
    url(r'^live/dashboard/', include('dashboard.urls')),
   # url(r'^live/dashboard/organizer_dashboard',views.manageevents),
    url(r'^home/$', views.home, name='home'),
    url(r'^live/$',views.home , name='home'),
    url(r'^live/verify_email/(?P<slug>[\w-]+)/$', views.verify_mail),
#    url(r'^live/verify_email/$', views.verify_mail, name='verify-email'),
    url(r'^live/forgot_password/$', views.forgotPassword, name='forgot-password'),
    url(r'^live/reset_password/(?P<slug>[\w-]+)/$', views.resetPassword),
    url(r'^live/set_new_password/$', views.setNewPassword),
#    url(r'^live/reset_password/$', views.resetPassword,name='reset-password'),
    url(r'^live/login/$', views.loginview, name='login'),
    url(r'^live/logout/$', views.logoutview, name='logout'),
    url(r'^live/signup/$', views.registration,name='signup'),
    url(r'^live/multichannel/$',views.multichannelpromotion,name='multichannel-promotion'),
    url(r'^live/sell-event-stalls/$',views.sellstallspaces, name='sell-event-stalls'),
    url(r'^live/paid-advertisement/$', views.advertisement,name='advertisement'),
    url(r'^live/how-it-works/$',views.howitworks, name='how-it-works'),
    url(r'^live/about/$',views.aboutus,name='about-us'),
    url(r'^live/contact/$',views.contactus,name='contact-us'),
    url(r'^live/blogs/$', views.blog, name='blog'),
    url(r'^live/blog-post/(?P<pk>[0-9]+)$', views.blogpost,name='blog-post'),
    url(r'^live/careers/$', views.career, name='careers'),
    url(r'^live/pricing/$', views.pricing, name='pricing'),
    url(r'^live/partners/$', views.partners, name='partners'),
    url(r'^live/privacy-policy/$', views.privacypolicy , name='privacy-policy'),
    url(r'^live/api/blogs/$' , BlogDetails.as_view(),name='blog-details'),
    url(r'^live/api/blogs/(?P<pk>[0-9]+)$', BlogSpecific.as_view(),name='blogspecific'),
    url(r'^live/api/users/$', Reg.as_view(),name='reg'),
    url(r'^live/api/login/$', LoginView.as_view(),'loginview'),
    url(r'^live/case-studies/$',views.case_studies, name='case-studies'),
    url(r'^live/cashback-info/(?P<slug>[\w-]+)$', views.provideCashbackDetails),
    url(r'^short-url/(?P<slug>[\w-]+)$', url_shortner.expand_url),

]

if settings.DEBUG:
    
    import debug_toolbar
    
    urlpatterns = [
      url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin_panel/urls.py
from django.urls import path
from admin_panel import views

app_name = 'admin-panel'

urlpatterns =[
    path('',views.admin_home,name = 'home'),
    #path('edit/<int:event_id>',views.editButton,name='edit'),
    path('event-lists/',views.eventList,name='eve_list'),
    path('past-event-lists/',views.pastEventList,name='past_list'),
    path('event-details/<int:event_id>',views.EventDetailView.as_view(),name='details'),
    path('event-promotion-upcoming/',views.promotionUpcoming,name='up_prom'),
    path('event-promotion-past/',views.promotionPast,name='past_prom'),
    path('login/',views.admin_login,name = 'admin_login'),
    path('partner-sites/', views.partner_sites, name = 'test'),
    path('user-detail/', views.user_detail, name = 'user-detail'),
    # path('add-rsvp/<int:event_id>', views.add_rsvp, name = 'add-rsvp'),
    path('add-sales/<int:event_id>', views.add_sales, name='add-sales'),

    path('sale-settled/', views.sale_settled.as_view(), name ='sale-settled'),
    path('sale-pending/',views.sale_pending.as_view(),name = 'sale-pending'),
    path('sale-list/', views.sale_settled.as_view(), name ='sale-list'),
    path('sale-list/<int:table_id>', views.sale_details, name='sale-details'),

    path('booking_details/<int:booking_id>',views.booking_details,name='booking-details'),
    # path('sale-list/edit/<int:table_id>', views.edit_sales, name='sale-edit'),
    # path('sale-settled-edit/<int:pk>', views.Sale_Edit.as_view(), name='sale-details')
    path('sale-list/<int:table_id>', views.sale_details, name='sale-details'),
    path('sale-list/<str:booking_id>',views.booking_details,name='booking-details'),
    path('details-partner/<int:table_id>',views.partner_site_details,name='details-page'),
    # path('adduser/',views.UserRegister.as_view(),name = 'add'),
    # @author Shubham
    path('add-rsvp-details/<int:event_id>', views.add_rsvp_details, name = 'add-rsvp-details'),
    path('add-sales-free-tkt-details/<int:event_id>', views.add_sales_free_tkt_details, name = 'add-sales-free-tkt-details'),
    path('send-confirm-org-email/', views.send_confirm_org_email, name = 'send-confirm-org-email'),
    path('update-ticket-url/', views.update_ticket_url, name = 'update-ticket-url'),
    path('change-event-status/', views.change_event_status, name = 'change-event-status'),
    path('create-leads-csv', views.create_leads_csv, name = 'create-leads-csv'),
    # ends here ~ @author Shubham
]

admin_panel/models.py
from django.db import models

choice = (
    ('','Select Option'),
    ('1','Male'),
    ('2','Female')
)



# class AddUser(models.Model):
#     first_name = models.CharField(max_length = 100)
#     last_name = models.CharField(max_length = 100)
#     email = models.EmailField()
#     gender = models.CharField(max_length = 20,choices = choice)
#     location = models.CharField(max_length = 100)
#     mobile_no = models.CharField(max_length = 10,blank = True,null = True)
#     organization = models.CharField(max_length = 100,blank = True,null = True)
#     password = models.CharField(max_length = 50)
#     md5 = models.CharField(max_length = 100)

#     class Meta:
#         db_table = 'add_user'
        

admin_panel/views.py
from django.shortcuts import render,HttpResponse,redirect,HttpResponseRedirect,reverse,get_object_or_404
# Create your views here.
# from admin_panel.forms import LoginForm,EditForm,AddRsvpForm,AddSalesDetailsForm,AddUserForm
from admin_panel.forms import LoginForm,EditForm,AddRsvpForm,AddSalesDetailsForm

from dashboard.models import Admin,AdminAccesses,AdminActionLog,StatusPromotionTicketing,Articles2,AttendeeFormBuilder,AttendeeFormOptions, AttendeeFormTypes, Tickets,AboutCountries ,TicketsSale,Categories,CategorizedEvents,Topics,EventVerificationResult,EventProcesses,StatusOnChannel,EventStatusOnChannel, PartnerSites,Rsvp,AdminAccessTypes,PaymentSettlement,BankDetails,ErcessIndiaeveStates,ErcessPartnersCategories,ErcessPartnersSubcategories,PartnerCurrencies,PartnerTimezones,ErcessOtherMappings, Leads, TicketDiscounts, ReferrerCashbackInfo, ReferrerCashbackTokens, ErcessOffers
from django.core.exceptions import ObjectDoesNotExist
from Ercesscorp.models import Users
from datetime import datetime
from django.contrib import messages
from django.utils import timezone
from django.core.validators import ValidationError
from Ercesscorp.models import UserRegistrationToken

from dashboard.serializers import EditViewSerializer,EditTicketSerializer
from rest_framework.views import APIView
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from django.conf import settings
from django.core.mail import  send_mail
from django.template.loader import render_to_string
from django.core.mail import EmailMessage

from smtplib import SMTPException
from django.views import View
from django.views.generic import  UpdateView
from django.urls import reverse_lazy
from django.views import generic
from django.core.mail import EmailMultiAlternatives
import hashlib
import string
import random
import json
import csv
import uuid
import time as Time
from datetime import datetime as dt


def admin_login(request):

    form = LoginForm()

    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            email = request.POST.get('email')
            password = request.POST.get('password')
            print(email)

            if Admin.objects.filter(email_id = email).exists():
                print("1st stage")

                if Admin.objects.filter(email_id = email , password = password).exists():
                    print("2nd stage")
                    admin_user = Admin.objects.get(email_id = email)
                    print(admin_user)

                    if admin_user.admin_active == 1:

                        #grabbing sessions from Admin model
                        request.session['admin_id'] = admin_user.table_id
                        request.session['fname'] = admin_user.fname
                        request.session['lname'] = admin_user.lname
                        request.session['mobile'] = admin_user.mobile
                        print(request.session['admin_id'])
                        print(request.session['fname'])

                        access = AdminAccesses.objects.filter(admin_id = admin_user.table_id).order_by('access_type')


                        # grabbing sessions from AdminAccess model
                        print(access)

                        for i in access:
                            type = AdminAccessTypes.objects.all().filter(table_id= i.access_type)
                            request.session['para_'+str(i.access_type)] = type[0].parameter
                            request.session['read_'+str(i.access_type)] = i.read_access
                            request.session['write_'+str(i.access_type)] = i.write_access
                            request.session['delete_'+str(i.access_type)] = i.delete_access
                        print("access is working")

                        for i,j in request.session.items():
                            print(str(i) +" : " +str(j))



                        #storing in access action log
                        access_log = AdminActionLog()
                        access_log.admin_id = request.session['admin_id']
                        access_log.timestamp = datetime.now()
                        access_log.parameter = "log-in"
                        access_log.action_taken = "logged-in"
                        access_log.event_id = 0
                        access_log.save()

                        return redirect('admin-panel:home')
                    else:
                        messages.error(request,"Sorry you dont have admin access")
                else:
                    messages.error(request,'Wrong Password')
            else:
                messages.error(request,'Wrong Admin')
        else:
            messages.error(request,'Form looks invalid')

    return render(request, 'admin_panel/login_admin.html',{'form':form})


def admin_home(request):
    if 'admin_id' not in request.session.keys():
        return redirect('/admin-site/login')
    return render(request,'admin_panel/admin_home.html')


def eventList(request):
    if 'admin_id' not in request.session.keys():
        return redirect('/admin-site/login')

    # call getEventProcessList function to fetch all rows from EventProcesses Table
    eventProcessListData = getEventProcessList()
    # ends here ~ call getEventProcessList function to fetch all rows from EventProcesses Table

    new_stat =StatusPromotionTicketing.objects.all().filter(complete_details=1,approval = 0).\
        exclude(event_active =5).order_by('-event_id')

    app_stat =StatusPromotionTicketing.objects.all().filter(complete_details=1,approval=1).\
        exclude(event_active=5).order_by('-event_id')

    unapp_stat =StatusPromotionTicketing.objects.all().filter(complete_details=1,approval=0,event_active=5)

    drafts_stat =StatusPromotionTicketing.objects.all().exclude(complete_details=1)

    time =timezone.now()

    ############################################################---------------------------    UPCOMING TAB
    ###########   NEW EVENT   ###########
    print("NEW EVENT ----------------------------------")
    new_id =[]
    new_name=[]
    new_create =[]
    new_start =[]
    new_username = []

    for i in new_stat:
        print(i.event_id)
        print(i.connected_user)
        event = Articles2.objects.all().filter(id = i.event_id)
        user =  Users.objects.all().filter(id=i.connected_user)
        print(user)
        if len(event)!=0:
            if event[0].edate>=time:
                new_id.append(event[0].id)
                new_name.append(event[0].event_name)
                new_create.append(event[0].date_added)
                new_start.append(event[0].sdate)

                if len(user)!=0:
                    new_username.append(user[0].firstname + " " +user[0].lastname)
                else:
                    new_username.append(0)
    print(new_name)
    print(new_username)

    new_items = zip(new_id,new_name,new_create,new_start,new_username)

    #############   APPROVED EVENTS   ###############
    print("APPROVED     ----------------------------------")
    print(app_stat)
    app_id=[]
    app_name=[]
    app_create=[]
    app_start=[]
    app_user=[]
    for i in app_stat:
        event = Articles2.objects.all().filter(id = i.event_id)
        user = Users.objects.all().filter(id = i.connected_user)

        if len(event)!=0:
            if event[0].edate >= time:
                app_id.append(event[0].id)
                app_name.append(event[0].event_name)
                app_create.append(event[0].date_added)
                app_start.append(event[0].sdate)
                if len(user)!=0:
                    app_user.append(user[0].firstname + " " + user[0].lastname)
                else:
                    app_user.append(0)
    print(app_name)
    print(app_user)

    app_items = zip(app_id,app_name,app_create,app_start,app_user)

    ##############    UNAPPROVED EVENTS   ####################
    print("UNAPPROVED              ----------------------------------")
    print(unapp_stat)
    unapp_id=[]
    unapp_name = []
    unapp_create =[]
    unapp_start =[]
    unapp_user = []

    for i in unapp_stat:

        event = Articles2.objects.all().filter(id = i.event_id)
        user = Users.objects.all().filter(id = i.connected_user)

        if len(event)!=0:
            if event[0].edate >= time:
                unapp_id.append(event[0].id)
                unapp_name.append(event[0].event_name)
                unapp_create.append(event[0].date_added)
                unapp_start.append(event[0].sdate)
                if len(user)!=0:
                    unapp_user.append(user[0].firstname +" "+user[0].lastname)
                else:
                    unapp_user.append(0)
    print(unapp_name)
    print(unapp_user)

    unapp_items = zip(unapp_id,unapp_name,unapp_create,unapp_start,unapp_user)

    ###################    DRAFTS    ######################
    print("DRAFTS      ----------------------------------")
    print(drafts_stat)
    d_id =[]
    d_name = []
    d_create = []
    d_start = []
    d_user = []

    for i in drafts_stat:

        event = Articles2.objects.all().filter(id=i.event_id)
        user = Users.objects.all().filter(id=i.connected_user)

        if len(event) != 0:
            if event[0].edate >= time:
                d_id.append(event[0].id)
                d_name.append(event[0].event_name)
                d_create.append(event[0].date_added)
                d_start.append(event[0].sdate)
                if len(user) != 0:
                    d_user.append(user[0].firstname + " " + user[0].lastname)
                else:
                    d_user.append(0)
    print(d_name)
    print(d_user)

    draft = zip(d_id,d_name,d_create,d_start,d_user)

    return render(request,'admin_panel/event_list.html',{'new':new_items,'app':app_items, 'unapp':unapp_items,'draft':draft,'eventProcessesData':eventProcessListData})

templates/admin_panel/admin_home.html
{% extends 'admin_panel/admin_base.html' %}

{% block home %}
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1>Welcome to admin panel.</h1>
		</div>

		<div class="col-md-6 col-lg-6">
			<a href="{% url 'admin-panel:eve_list' %}">
				<div style="padding: 50px 0;text-align: center;background: #da2021;color: #fff;">
					<h3>Upcoming events list</h3>
				</div>
			</a>
		</div>
		<div class="col-md-6 col-lg-6">
			<a href="{% url 'admin-panel:past_list' %}">
				<div style="padding: 50px 0;text-align: center;background: #da2021;color: #fff;">
					<h3>Past events list</h3>
				</div>
			</a>
		</div>
		<div class="clearfix"></div>

		<div class="col-md-6 col-lg-6">
			<a href="{% url 'admin-panel:up_prom' %}">
				<div style="padding: 50px 0;margin-top:30px;text-align: center;background: #da2021;color: #fff;">
					<h3>Upcoming events promotion links</h3>
				</div>
			</a>
		</div>
		<div class="col-md-6 col-lg-6">
			<a href="{% url 'admin-panel:past_prom' %}">
				<div style="padding: 50px 0;margin-top:30px;text-align: center;background: #da2021;color: #fff;">
					<h3>Past events promotion links</h3>
				</div>
			</a>
		</div>
	</div>
</div>

{% endblock %}

templates/admin_panel/event_list.html
{% extends 'admin_panel/admin_base.html' %}

{% block eventlist %}
<link rel="stylesheet" type="text/css" href="/static/assets/vendor_components/datatable/datatables.min.css"/>
<style>
  table tr{
    cursor: pointer;
  }
</style>
<section class="content">
    <div class="container arrow-steps clearfix">
        <div class="row">
            <div class="col-md-12">
                <h1 class="text-dark mb-30">Upcoming/ongoing events</h1>
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#new">New Events</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#approved">Approved Events</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#unapproved">Unapproved Events</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#drafts">Drafts</a>
                    </li>
                </ul>

                <div class="tab-content">
                    <div id="new" class="tab-pane active">
                        <div class="table-responsive">
                            <table id="example" class="table table-hover display nowrap">
                                <thead>
                                    <tr>
                                      <th>Event id</th>
                                      <th>Event name</th>
                                      <th>Created date</th>
                                      <th>Start date</th>
                                      <th>Organizer</th>
                                      <th>Change Status</th>
                                    </tr>
                                </thead>

                                {% for id,name,create,start,user in new %}
                                <tr data-href="{% url 'admin-panel:details' event_id=id %}">
                                    <td>{{id}}</td>
                                    <td>
                                      <div class="pull-left pt-10">
                                        {{name}}
                                      </div>
                                    </td>
                                    <td>{{create.date}}</td>
                                    <td>{{start.date}}</td>
                                    <td>{{user}}</td>
                                    <td class="disabled_blank">
                                      <a class="btn btn-info btn-block" onclick="unapproveEventModalFn('{{id}}','{{user}}')">Disapprove</a>

                                      <a class="btn btn-info btn-block" onclick="approveEventFn('{{id}}','{{user}}', '{{eventProcessesData | length}}')">Approve</a>
                                    </td>
                                </tr>
                                {% endfor %}
                                <tfoot>
                                    <tr>
                                      <th>Event id</th>
                                      <th>Event name</th>
                                      <th>Created date</th>
                                      <th>Start date</th>
                                      <th>Organizer</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>



                    <div id="approved" class="tab-pane ">
                        <div class="table-responsive">
                            <table class="table table-hover display nowrap">
                                <thead>
                                    <tr>
                                      <th>Event id</th>
                                      <th>Event name</th>
                                      <th>Created date</th>
                                      <th>Start date</th>
                                      <th>Organizer</th>
                                      <th>Change Status</th>
                                    </tr>
                                </thead>
                                {% for id,name,create,start,user in app %}
                                <!-- <tr data-href="{% url 'admin-panel:details' event_id=id %}"> -->
                                  <tr data-href="{% url 'admin-panel:details' event_id=id %}">
                                    <td>{{id}}</td>
                                    <td>
                                      <div class="pull-left pt-10">
                                        <!-- <a href="{% url 'admin-panel:details' event_id=id %}" target="_blank">{{name}}</a> -->
                                        {{name}}
                                      </div>
                                    </td>
                                    <td>{{create.date}}</td>
                                    <td>{{start.date}}</td>
                                    <td>{{user}}</td>
                                    <td class="disabled_blank">
                                      <a class="btn btn-info btn-block" onclick="unapproveEventModalFn('{{id}}','{{user}}')">Disapprove</a>
                                    </td>
                                </tr>
                                {% endfor %}
                                <tfoot>
                                    <tr>
                                      <th>Event id</th>
                                      <th>Event name</th>
                                      <th>Created date</th>
                                      <th>Start date</th>
                                      <th>Organizer</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>



                    <div id="unapproved" class="tab-pane ">
                        <div class="table-responsive">
                            <table class="table table-hover display nowrap">
                              <thead>
                                <tr>
                                  <th>Event id</th>
                                  <th>Event name</th>
                                  <th>Created date</th>
                                  <th>Start date</th>
                                  <th>Organizer</th>
                                  <th>Change Status</th>
                                </tr>
                              </thead>
                                {% for id,name,create,start,user in unapp %}
                                <tr data-href="{% url 'admin-panel:details' event_id=id %}">
                                    <td>{{id}}</td>
                                    <td>
                                      <div class="pull-left pt-10">
                                        {{name}}
                                      </div>
                                    </td>
                                    <td>{{create.date}}</td>
                                    <td>{{start.date}}</td>
                                    <td>{{user}}</td>
                                    <td class="disabled_blank">
                                      <a class="btn btn-info btn-block" onclick="approveEventFn('{{id}}','{{user}}', '{{eventProcessesData | length}}')">Approve</a>
                                    </td>
                                </tr>
                                {% endfor %}
                                <tfoot>
                                  <tr>
                                    <th>Event id</th>
                                    <th>Event name</th>
                                    <th>Created date</th>
                                    <th>Start date</th>
                                    <th>Organizer</th>
                                  </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>

                    <div id="drafts" class="tab-pane">
                        <div class="table-responsive">
                            <table class="table table-hover display nowrap">
                              <thead>
                                <tr>
                                  <th>Event id</th>
                                  <th>Event name</th>
                                  <th>Created date</th>
                                  <th>Start date</th>
                                  <th>Organizer</th>
                                </tr>
                              </thead>
                                {% for id,name,create,start,user in draft %}
                                <tr data-href="{% url 'admin-panel:details' event_id=id %}">
                                    <td>{{id}}</td>
                                    <td>
                                      <div class="pull-left pt-10">
                                        {{name}}
                                      </div>
                                    </td>
                                    <td>{{create.date}}</td>
                                    <td>{{start.date}}</td>
                                    <td>{{user}}</td>
                                </tr>
                                {% endfor %}
                                <tfoot>
                                <tr>
                                  <th>Event id</th>
                                  <th>Event name</th>
                                  <th>Created date</th>
                                  <th>Start date</th>
                                  <th>Organizer</th>
                                </tr>
                              </tfoot>
                            </table>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
</section>

<!-- @author Shubham ~ change event status (approve/unapprove)  -->
{% include 'admin_panel/event_status_to_unapprove.html' %}
{% include 'admin_panel/event_status_to_approve.html' %}
<!-- ends here ~ @author Shubham ~ change event status (approve/unapprove)  -->


<script src="/static/assets/vendor_components/datatable/datatables.min.js"></script>
<script src="/static/js/pages/data-table.js"></script>
<script src="/static/js/pages/project-table.js"></script>
<script>

    // old code
    // $("table tbody tr").click(function() {
    //     window.open($(this).attr("data-href"), '_blank')
    // });
    // ends here ~ old code

    // new code
    $("table tbody tr td").not('.disabled_blank').click(function() {
        window.open($(this).parent().attr("data-href"), '_blank')
    });
    // ends here ~ new code

</script>
{% endblock eventlist %}

templates/admin_panel/pending_settlement.html
{% extends 'admin_panel/admin_base.html' %}

{% block saledetail %}

<section class='content'>
  <div class="container arrow-steps clearfix">
    <div class="row">
      <div class="col-md-12">
        <h1>Pending settlement </h1>
        <div class="table-responsive">
            <table class="table table-hover table-event-list">
                <tr>
                  <th>Booking id</th>
                  <th>Attendee Name</th>
                  <th>Amount Paid</th>
                  <th>Purchase Date</th>
                  <th>Receival Status</th>
                </tr>

                <tr>
                    <a href="{% url 'admin-panel:booking-details' booking_id=sales.booking_id  %}"><td>
                        {{sales.booking_id}}
                    </td></a>
                    <td>{{sales.attendee_name}}</td>
                    <td>{{sales.ampunt_paid}}</td>
                     <td>{{sales.purchase_date}}</td>
                    <td>{{ payment.receival_status}}</td>
                </tr>
            </table>
        </div>
      </div>

    </div>
  </div>

</section>

{% endblock saledetail %}

templates/admin_panel/prom_upcoming.html
{% extends 'admin_panel/admin_base.html' %}

{% block upprom %}
<link rel="stylesheet" type="text/css" href="/static/assets/vendor_components/datatable/datatables.min.css"/>

<section class='content'>
  <div class="container arrow-steps clearfix">
    <div class="row">
      <div class="col-md-12">
        <h1>Upcoming events' promotion status</h1>
        <div class="table-responsive">
            <table class="table table-hover display nowrap">
                <tbody>
                  <tr>
                    <th>Event name</th>
                    <th>Site name</th>
                    <th>Link</th>
                    <th>Promotion status</th>
                    <th>Partner status</th>
                  </tr>
                </tbody>
                {% for id,name,site,link,prom,part in up %}
                <tr>
                    <td>
                      <div class="pull-left ml-10 pt-10">
                        <a href="{% url 'admin-panel:details' event_id=id %}" target="_blank">{{name}}</a>
                      </div>
                    </td>
                    <td>{{site}}</td>
                      <td class="">
                        {% if link == 'None' %}
                        --
                        {% else %}
                        <a href="{{link}}" target="_blank">Link</a>
                        {% endif %}
                      </td>
                    <td>{{prom}}</td>
                    <td>{{part}}</td>
                </tr>
                {% endfor %}
                <tfoot>
                  <tr>
                    <th>Event name</th>
                    <th>Site name</th>
                    <th>Link</th>
                    <th>Promotion status</th>
                    <th>Partner status</th>
                  </tr>
                </tfoot>
            </table>
        </div>
      </div>
    </div>
  </div>
</section>

<script src="/static/assets/vendor_components/datatable/datatables.min.js"></script>
<script src="/static/js/pages/data-table.js"></script>
<script src="/static/js/pages/project-table.js"></script>

{% endblock upprom %}