Ercess/urls.py
from django.contrib import admin
from django.conf.urls import  url
from Ercesscorp import  views
from django.urls import  path ,re_path ,include
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from Ercesscorp.apiviews import *
from dashboard import url_shortner

# app_name = 'Ercess'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin-site/',include('admin_panel.urls')),

    url(r'^$', views.home , name='home'),
    url(r'^accounts/login/$',views.loginview ,name='login'),
    url(r'^live/dashboard/', include('dashboard.urls')),
   # url(r'^live/dashboard/organizer_dashboard',views.manageevents),
    url(r'^home/$', views.home, name='home'),
    url(r'^live/$',views.home , name='home'),
    url(r'^live/verify_email/(?P<slug>[\w-]+)/$', views.verify_mail),
#    url(r'^live/verify_email/$', views.verify_mail, name='verify-email'),
    url(r'^live/forgot_password/$', views.forgotPassword, name='forgot-password'),
    url(r'^live/reset_password/(?P<slug>[\w-]+)/$', views.resetPassword),
    url(r'^live/set_new_password/$', views.setNewPassword),
#    url(r'^live/reset_password/$', views.resetPassword,name='reset-password'),
    url(r'^live/login/$', views.loginview, name='login'),
    url(r'^live/logout/$', views.logoutview, name='logout'),
    url(r'^live/signup/$', views.registration,name='signup'),
    url(r'^live/multichannel/$',views.multichannelpromotion,name='multichannel-promotion'),
    url(r'^live/sell-event-stalls/$',views.sellstallspaces, name='sell-event-stalls'),
    url(r'^live/paid-advertisement/$', views.advertisement,name='advertisement'),
    url(r'^live/how-it-works/$',views.howitworks, name='how-it-works'),
    url(r'^live/about/$',views.aboutus,name='about-us'),
    url(r'^live/contact/$',views.contactus,name='contact-us'),
    url(r'^live/blogs/$', views.blog, name='blog'),
    url(r'^live/blog-post/(?P<pk>[0-9]+)$', views.blogpost,name='blog-post'),
    url(r'^live/careers/$', views.career, name='careers'),
    url(r'^live/pricing/$', views.pricing, name='pricing'),
    url(r'^live/partners/$', views.partners, name='partners'),
    url(r'^live/privacy-policy/$', views.privacypolicy , name='privacy-policy'),
    url(r'^live/api/blogs/$' , BlogDetails.as_view(),name='blog-details'),
    url(r'^live/api/blogs/(?P<pk>[0-9]+)$', BlogSpecific.as_view(),name='blogspecific'),
    url(r'^live/api/users/$', Reg.as_view(),name='reg'),
    url(r'^live/api/login/$', LoginView.as_view(),'loginview'),
    url(r'^live/case-studies/$',views.case_studies, name='case-studies'),
    url(r'^live/cashback-info/(?P<slug>[\w-]+)$', views.provideCashbackDetails),
    url(r'^short-url/(?P<slug>[\w-]+)$', url_shortner.expand_url),

]

if settings.DEBUG:
    
    import debug_toolbar
    
    urlpatterns = [
      url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path, include
from django.conf.urls import  url
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.views.generic import TemplateView

from Ercesscorp.third_party_security import smartlogin
from Ercesscorp import views
from Ercesscorp.views import edit_event,step_three,edit_event_two,edit_event_four,edit_event_five,edit_action_four,edit_action_four,edit_action_five,new_ticket
from dashboard.api.views import StallCreateAPIView, FacilitiesAPIView, StallUploadAPIView, StallUpdateAPIView, \
    EventSuccessView
from dashboard.views import getHow, change_password # , third_step#,photo_list ,fourth_step
from .api.views import ( ArticlesCreateAPIView, CategoryCreateAPIView,
                        TopicsListAPIView, DescriptionCreateAPIView,
                        ThirdStepTemp, QuestionCreateAPIView,
                        CreateTicketsView, BankDetailsView, EditBankDetailsView)

from .views import  EditDetailView


app_name = 'dashboard'

urlpatterns = [
    url(r'^$', getHow, name='how'),
    path('create-stall-step1/<int:event_id>/', FacilitiesAPIView.as_view(), name='facilities'),
    path('create-stall-step2/<int:event_id>/', StallUploadAPIView.as_view(), name='stall_upload'),
    path('create-stalls/<int:event_id>/', StallCreateAPIView.as_view(), name='create_stall'),
    path('update-stalls/<int:event_id>/', StallUpdateAPIView.as_view(), name='stall_update'),

    path('add-event', ArticlesCreateAPIView.as_view(), name="step_one"),
    path('add-event-types/<str:md5>/<int:event_id>', CategoryCreateAPIView.as_view(), name="step_two"),
    path('add-event-images/<str:md5>/<int:event_id>', views.step_three, name="step_three"),
    # path('add-event-images-action/<str:md5>/<int:event_id>', views.step_three_action, name="step_three_action"),
    path('ajax/topics', TopicsListAPIView.as_view()),
    path('add-event-description/<str:md5>/<int:event_id>', DescriptionCreateAPIView.as_view(), name="step_four"),
    path('add-event-tickets/<str:md5>/<int:event_id>', CreateTicketsView.as_view(), name="step_five"),
    path('add-event-question/<str:md5>/<int:event_id>', QuestionCreateAPIView.as_view(), name="step_six"),
    path('stall_added/', TemplateView.as_view(template_name='stall/stall_success.html'), name='stall_added'),
    path('event_added/<int:event_id>/', EventSuccessView.as_view(), name='event_added'),
    path('RSVP',views.RSVP,name='leads'),
    path('updateContact/',views.updateMobileNo, name="updateContact"),
    path('rsvp/<int:event_id>',views.rsvp_event,name='rsvp-event'),
    path('organizer_dashboard',views.manageevents, name='organizer-dashboard'),
    path('event-details/<int:event_id>',views.event_details, name='event-details'),
    path('sales', views.getSales, name='sales'),
    path('sales_details/<int:event_id>/',views.getSalesDetails, name ='sale_details'),
    path('inquiries', views.getInquiries, name='inquiries'),
    path('help',views.getHelp,name='help'),
    path('profile',views.profile,name='profile'),
    path('settings', change_password,name='settings'),
    path('legal',views.legal,name='legal'),
    path('organizer-agreement',views.organizer_agreement,name='organizer-agreement'),
    path('bank-details',BankDetailsView.as_view(), name="bank_details"),
    # path('create-stalls',views.create_stall, name="create_stall"),
    path('edit-event/<int:event_id>', EditDetailView.as_view(), name="detail"),
    path('boost-event/<int:event_id>', views.boost, name="boost-event"),
    path('edit-event/basic/<int:event_id>',views.edit_event, name='edit-event'),
    path('edit-event-two/<int:event_id>',views.edit_event_two, name='edit-event-two'),
    # path('edit-event-three/<int:event_id>',views.edit_event_three, name='edit-event-three'),
    path('edit-event-four/<int:event_id>',views.edit_event_four, name='edit-event-four'),
    path('edit-event-five/<int:event_id>/<int:ticket_id>',views.edit_event_five, name='edit-event-five'),
    path('edit_event_ticket/<event_id>',views.edit_event_ticket, name='edit-event-ticket'),
    path('new_ticket/<int:event_id>',views.new_ticket, name='new-ticket'),
    path('edit_action_two/<event_id>',views.edit_action_two, name='edit-action-two'),
    path('edit_action_five/<event_id>/<int:ticket_id>',views.edit_action_five, name='edit-action-five'),
    path('edit_action_four/<event_id>',views.edit_action_four, name='edit-action-four'),
    path('delete_ticket/<str:md5>/<int:event_id>/<int:ticket_id>/<int:return_page>',views.delete_ticket, name='delete-ticket'),
    path('update_event_tickets/<str:md5>/<int:event_id>/<int:ticket_id>',views.update_event_tickets, name='update-event-tickets'),
    path('edit_event_three/<int:event_id>',views.edit_event_three, name='edit-event-three'),
    path('edit-bank-details',EditBankDetailsView.as_view(), name="edit_bank_details"),
    # path('unlock-rsvp/<int:event_id>/<int:table_id_par>',views.unlock_rsvp,name='unlock-rsvp'),
    # path('subscribe-premium-package/<int:event_id>/<int:table_id_par>/<charges_id_par>',views.subscribe_premium_package,name='subscribe-premium-package'),
    # path('payment-success-rsvp',views.payment_success_rsvp,name='payment-success-rsvp'),
    # path('payment-fail-rsvp',views.payment_fail_rsvp,name='payment-fail-rsvp'),
    
    # urls for duplicate events
    path('duplicate-event-basics/<int:event_id>', views.duplicate_event_basics,name='duplicate-event-basics'),
    path('duplicate-event-two/<int:old_event_id>/<int:new_event_id>', views.duplicate_event_two,name='duplicate-event-two'),
    path('duplicate-event-three/<int:old_event_id>/<int:new_event_id>', views.duplicate_event_three,name='duplicate-event-three'),
    path('duplicate-event-four/<int:old_event_id>/<int:new_event_id>', views.duplicate_event_four,name='duplicate-event-four'),
    path('duplicate-event-five/<int:old_event_id>/<int:new_event_id>/<int:ticket_id>', views.duplicate_event_five,name='duplicate-event-five'),
    path('duplicate-event-tickets/<int:old_event_id>/<int:new_event_id>', views.duplicate_event_tickets,name='duplicate-event-tickets'),
    path('save-duplicate-event-five', views.save_duplicate_event_five,name='save-duplicate-event-five'),
    path('duplicate-new-ticket/<int:old_event_id>/<int:new_event_id>', views.duplicate_new_ticket,name='duplicate-new-ticket'),
    path('duplicate-event-six/<int:old_event_id>/<int:new_event_id>', views.duplicate_event_six,name='duplicate-event-six'),
    # ends here ~ urls for duplicate events

    path('check-event-already-created', views.check_event_already_created,name='check-event-already-created'),
    path('check-event-already-created-edit', views.check_event_already_created_edit,name='check-event-already-created-edit'),
    path('update-ann-access-table', views.updateAnnAccessTable,name='update-ann-access-table'),
    path('show-rsvp-premium-packages/<int:event_id>/<str:service_type>/<str:purpose_of_payment>',views.show_rsvp_premium_packages,name='show-rsvp-premium-packages'),
    
    # urls for payment package
    #IMPORTANT NOTE (For PAYUMONEY PAYMENT GATEWAY): All parameter name which start wifh udf's, that is temporary because we don't know about next values.. must need to change in future if include more values (e.g, now, udf2=event_id and udf3=charges_id) & MAX 10 UDF is allowed by PayUMoney
    path('buy-premium-package/<int:event_id>/<int:charges_id>/<int:udf4>/<int:udf5>/<str:purpose_of_payment>',views.buy_premium_package,name='buy-premium-package'),
    path('package-payment-success',views.package_payment_success,name='package-payment-success'),
    path('package-payment-fail',views.package_payment_fail,name='package-payment-fail'),
    # ends here ~ urls for payment package

    # sms marketing urls
    path('sms-marketing-initial-details/<int:event_id>',views.sms_marketing_initial_details,name='sms-marketing-initial-details'),
    path('sms-marketing-advance-details/<int:event_id>/<int:template_id>',views.sms_marketing_advance_details,name='sms-marketing-advance-details'),
    path('sms-marketing-schedule',views.sms_marketing_schedule,name='sms-marketing-schedule'),
    # ends here ~ sms marketing urls

    # email marketing urls
    path('select-email-marketing-template/<int:event_id>',views.select_email_marketing_template,name='select-email-marketing-template'),
    path('email-marketing-initial-details/<int:event_id>/<str:template_name>',views.email_marketing_initial_details,name='email-marketing-initial-details'),
    path('email-marketing-advance-details/<int:event_id>/<int:campaign_template_id>',views.email_marketing_advance_details,name='email-marketing-advance-details'),
    path('email-marketing-schedule',views.email_marketing_schedule,name='email-marketing-schedule'),
    # ends here ~ email marketing urls





    # path('buy-premium-package/<int:event_id>/<charges_id_par>',views.buy_premium_package,name='buy-premium-package'),
    # path('package-payment-success',views.package_payment_success,name='package-payment-success'),
    # path('package-payment-fail',views.package_payment_fail,name='package-payment-fail'),
    # path('buy-premium-package/<int:event_id>',views.buy_package_manage_events_dashboard,name='buy-package-manage-events-dashboard'),

    # path('edit-event-five/<int:event_id>/<int:ticket_id>/<str:md5>/<int:return_page>',views.edit_event_five, name='edit-event-five'),
    
    # path('delete_ticket/<int:event_id>/<int:ticket_id>',views.delete_ticket, name='delete-ticket'),



    #path('legal',views.legal,name='legal'),
    #url(r'create-event/step-three/(?P<eventid>[0-9]+)$',login_required(third_step),name='third-step'),
    #url(r'test$',photo_list),
    #url(r'create-event/step-four/$',login_required(fourth_step),name='fourth-step')
    # url(r'^home',home,name='home'),

dashboard/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from Ercesscorp.porter import HOW__CHOICES
from django import forms
from django.core.files import File

from dashboard.models import Stall, StallUpload
from .models import Articles2,BoostEvent #,Photo




class HowForm(forms.Form):

    choices =  forms.ChoiceField(choices=HOW__CHOICES)
    other =  forms.CharField(widget=forms.Textarea(
        attrs={
            # 'class': 'form-control',
            'placeholder': 'if Others fill this *'
        }
    ))


class Articles2Form(forms.ModelForm):
    description = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Articles2
        fields = ('description',)

class BoostEventForm(forms.ModelForm):
    city=forms.CharField(max_length=500, widget=forms.TextInput(attrs={'id':"where_load",'class':"form-control form-control-lg"}))
    class Meta:
        model = BoostEvent
        fields = ['city',]


class ChangePasswordForm(forms.Form):
	oldpassword = forms.CharField(
			widget=forms.PasswordInput(

				attrs={
					'class': 'form-control',
					'placeholder': 'Your old Password *'

				}
			)
		)
	newpassword1 = forms.CharField(
        widget=forms.PasswordInput(

            attrs={
                'class': 'form-control',
                'placeholder': 'New Password *'

            }
        )
    )
	newpassword2 = forms.CharField(
        widget=forms.PasswordInput(

            attrs={
                'class': 'form-control',
                'placeholder': 'Confirm New Password *'

            }
        )
    )
	def clean(self):
            if len(self.cleaned_data['newpassword1'])<8:
                raise forms.ValidationError("New password is less than 8 characters")
            if self.cleaned_data['newpassword1'] != self.cleaned_data['newpassword2']:
                raise forms.ValidationError("The two password fields did not match.")
            return self.cleaned_data


# class StallForm(forms.ModelForm):
#     class Meta:
#         model = Stall
#         fields = '__all__'

'''
class PForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = Articles2
        fields = ('company_logo','event_banner','editable_image','x', 'y', 'width', 'height', )

    def save(self):
        photo = super(PForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.company_logo)

        print('photo.file in form' +str(photo.company_logo))
        cropped_image = image.crop((x, y, w+x, h+y))
        print('cropped image in form' + str(cropped_image))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        print('resize image in form' + str(resized_image))
        resized_image.save(photo.company_logo.path)
        print(photo.company_logo.path)
        # print(photo)
        return photo




class PhotoForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = Photo
        fields = ('file','x', 'y', 'width', 'height', )

    def save(self):
        photo = super(PhotoForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.file)
        print(image)
        print('photo.file in form' +str(photo.file))
        cropped_image = image.crop((x, y, w+x, h+y))
        print('cropped image in form' + str(cropped_image))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        print('resize image in form' + str(resized_image))
        resized_image.save(photo.file.path)
        print(photo.file.path)
        return photo


'''
class StallUploadForm(forms.ModelForm):
    class Meta:
        model = StallUpload
        fields = ['img', 'file']

templates/dashboard/boost_event.html
{% extends 'dashboard/create_event.html' %}

{% block title %}Boost Event{% endblock title %}
{% block edit_one %}


{% if messages %}
 {% for message in messages %}
<div class="alert alert-warning" style="color:white;">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <strong> {{message.tags}} : </strong> {{ message }}.
</div>
 {% endfor %}
{% endif %}

<section class="content">
  <div class="container arrow-steps clearfix">
    <div class="row">
      <div class="col-md-12">
        <div class="md-stepper-horizontal red" style="padding: 10%">
          <h1> city for event </h1>
          <hr/>
          <ul style="display:block; list-style:none;">
          {% for i in s %}
          <li><h4>{{i.city}}</h4></li>
          {% endfor %}

          {% for i in ac %}

          {% if i.city %}
          <li><h4>{{i.city}}</h4></li>
          {% endif %}

          {% endfor %}

          </ul>
          <details style="list-style:none;">
            <summary class="btn" style="display:block; color:blue;">add more city</summary>
            <form method="POST" style="margin:3%; " class="form-group">
              {% csrf_token %}
               {{form}}
               <br/>
              <input type="submit" class="btn btn-default" value="submit" />
            </form>
          </details>
          <br/>
          <br/>

          <a href="#" class="btn btn-success" style="float: right;">proceed</a>
        </div>
      </div>
    </div>
  </div>
  <script>
    var onLoaded = function() {
      // assumed your field has id of where_load, it might be different
      var location_input = document.getElementById('where_load');
      var autocomplete = new google.maps.places.Autocomplete(location_input);

    }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key={{api_key}}&libraries=places&callback=onLoaded" async defer></script>
</section>

{% endblock edit_one %}

templates/dashboard/edit_event_two.html
{% extends "dashboard/create_event.html" %}
{% load rest_framework %}

{% block title %}Set target of your event - Ercess Live{% endblock title %}
{% block step_two %}
<section class="content">
	<div class="container arrow-steps clearfix">
		<div class="row heading">
			<div class="col-md-12 border-bottom-heading">
				<!-- <h1 class="text-dark pb-20 pt-20">Set your targets</h1> -->
				<div class="row">
		            <div class="col-md-8">
		             <h1 class="text-dark pb-20 pt-20">Set your targets</h1>
		            </div>
		            <div class="col-md-4">
		                <div class="float-right" style="padding-top: 15px;">
		                  <a class="btn btn1 btn-danger text-white" href="{% url 'dashboard:detail' event_id %}">
		                  	<i class="fa fa-arrow-left" aria-hidden="true"></i>
		                  	Back
		                  </a>
		                </div>
		            </div>
		          </div>
				<div class="md-stepper-horizontal red">
					<div class="md-step">
						<a href="{% url 'dashboard:edit-event' event_id %}">
							<div class="md-step-circle"><span>1</span></div>
							<div class="md-step-title">Basic details</div>
							<div class="md-step-bar-left"></div>
							<div class="md-step-bar-right"></div>
						</a>
					</div>
					<div class="md-step active">
						<a href="{% url 'dashboard:edit-event-two' event_id  %}">
							<div class="md-step-circle"><span>2</span></div>
							<div class="md-step-title">Set targets</div>
							<div class="md-step-bar-left"></div>
							<div class="md-step-bar-right"></div>
						</a>
					</div>
					<div class="md-step">
						<a href="{% url 'dashboard:edit-event-three' event_id  %}">
								<div class="md-step-circle"><span>3</span></div>
								<div class="md-step-title">Upload images</div>
								<div class="md-step-bar-left"></div>
								<div class="md-step-bar-right"></div>
						</a>
					</div>
					<div class="md-step">
						<a href="{% url 'dashboard:edit-event-four' event_id  %}">
							<div class="md-step-circle"><span>4</span></div>
							<div class="md-step-title">Description</div>
							<div class="md-step-bar-left"></div>
							<div class="md-step-bar-right"></div>
						</a>
					</div>
					<div class="md-step">
						<a href="{% url 'dashboard:edit-event-ticket' event_id  %}">
							<div class="md-step-circle"><span>5</span></div>
							<div class="md-step-title">Add tickets</div>
							<div class="md-step-bar-left"></div>
							<div class="md-step-bar-right"></div>
						</a>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<form action="{% url 'dashboard:edit-action-two' event_id %}" method="POST" id="msform" class="col-md-12 mt-50 mb-50" autocomplete="off">
				{% csrf_token %}
				<fieldset>
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<div class="input-group mb-30">
									<select name="category_id" type="text" id="select_dropdown" class="form-control" style="height:auto">
										<!-- <option value="default" selected disabled>Select a topic</option> -->
										{% for val,id  in c %}

										{% if id == k %}
										<option id={{id}} value="{{id}}" selected> {{ val }} </option>

										{% else %}
										<option id={{id}} value="{{id}}"> {{ val }} {{h}}</option>
										{% endif %}
										{% endfor %}
									</select>
									<div class="input-error alert alert-danger"></div>
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<div class="input-group mb-30">
									<select name="topic_id" id='top' type="text" class="form-control" style="height:auto">

										{% for val1,id1  in t %}

										{% if id1 == l %}
										<option id={{id1}} value="{{id1}}" selected> {{ val1 }} </option>

										{% else %}
										<option id={{id1}} value="{{id1}}"> {{ val1 }} </option>
										{% endif %}
										{% endfor %}
									</select>
									<div class="input-error alert alert-danger"></div>
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<div class="btn-group mb-30 mt-30" data-toggle="buttons">

								{% if pr == 0 %}
								<label class="btn btn-primary active toggle-pair">
									<input type="radio" name="type1" id="pub" class='type1' value='public' style="margin-right:19px" checked> Public Event
								</label>
								<label class="btn btn-primary toggle-pair">
									<input type="radio" name="type1" class='type1' id="pri" value='private'> Private Event
								</label>
								{% endif %}
								{% if pr == 1 %}
								<label class="btn btn-primary toggle-pair">
									<input type="radio" name="type1" id="pub" class='type1' value='public' style="margin-right:19px"> Public Event
								</label>
								<label class="btn btn-primary active toggle-pair">
									<input type="radio" name="type1" class='type1' id="pri" value='private' checked> Private Event
								</label>
								{% endif %}
							</div>
						</div>
						<div class="col-md-6">
							<div class="btn-group mb-30 mt-30" data-toggle="buttons">
								{% if tick == 1 %}
								<label class="btn btn-primary active toggle-pair">
									<input type="radio" name="type2" id="paidevent" class='type2' value='paid' style="margin-right:19px" checked> Paid Event
								</label>
								<label class="btn btn-primary toggle-pair">
									<input type="radio" name="type2" class='type2' id="freeevent" value='free'> Free Event
								</label>
								{% elif tick == 0 %}
								<label class="btn btn-primary toggle-pair">
									<input type="radio" name="type2" id="paidevent" class='type2' value='paid' style="margin-right:19px"> Paid Event
								</label>
								<label class="btn btn-primary active toggle-pair">
									<input type="radio" name="type2" class='type2' id="freeevent" value='free' checked> Free Event
								</label>
								{% endif %}
							</div>
						</div>
					</div>
					<!--  <div id='type1'  style='float: left'>
		         <input id='pub' class='type1' name='type1' type="checkbox" value='public' checked >
		          <label  for='pub' style='color: black'>Public Event</label> <br/>
		         <input type="checkbox" class='type1' name='type1' id='pri' value='private'>
		          <label for='pri' style='color: black'>Private Event</label>
		          </div>
		         <div id='type2'>
		         <input id='paidevent' class='type2' name='type2' type="checkbox" value='paid' checked >
		          <label  for='paidevent' style='color: black'>Paid Event</label> <br/>
		         <input type="checkbox" class='type2' name='type2' value='free' id='freeevent' >
		          <label for='freeevent' style='color: black'>Free Event</label>
		          </div-->
						<div class="text-center">
								<button type="submit" id="n" class="btn btn2 btn-danger mt-40">Update</button>
						</div>
				</fieldset>
			</form>

		</div>
	</div>

</section>
<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>

<script>
	//        function getCookie(name) {
	//     var cookieValue = null;
	//     if (document.cookie && document.cookie != '') {
	//         var cookies = document.cookie.split(';');
	//         for (var i = 0; i < cookies.length; i++) {
	//             var cookie = jQuery.trim(cookies[i]);
	//             // Does this cookie string begin with the name we want?
	//             if (cookie.substring(0, name.length + 1) == (name + '=')) {
	//                 cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
	//                 break;
	//             }
	//         }
	//     }
	//     return cookieValue;
	// }
	// var csrftoken = getCookie('csrftoken');
	// function csrfSafeMethod(method) {
	//     // these HTTP methods do not require CSRF protection
	//     return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
	// }
	// $.ajaxSetup({
	//     beforeSend: function(xhr, settings) {
	//         if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
	//             xhr.setRequestHeader("X-CSRFToken", csrftoken);
	//         }
	//     }
	// });

	$(document).ready(function() {

		$('#select_dropdown').change(function() {
			var e = document.getElementById("select_dropdown");
			var value = e.options[e.selectedIndex].value;

			$("#n").trigger("click");
		});
	});

	//        $.ajax({
	//            url: "{% url 'dashboard:edit-action-two' event_id %}",
	//            type: "post",
	//            data: {'value':value},
	//            success: function(data) {

	//               value;
	//            }});


	//    });

	// });


	//    $(document).ready(function(){


	//          $.ajax({
	//              url: "http://127.0.0.1:8000/live/dashboard/edit-event-two/36758",
	//              type: "get",
	//              datatype: json,
	//              success: function(data) {
	//                   alert("data");
	//              }});


	//      });

	//   });

</script>


{% endblock step_two %}